package com.ipayso.util.enums;

/**
 * Countries.class -> Enum for Countries
 * @author Cleber Oliveira
 * @version 1.0
 */
public enum Countries {

	AE("United Arab Emirates"),
	AF("Afghanistan"),
	AM("Armenia"),
	AN("Netherlands Antilles"),
	AR("Argentina"),
	AS("American Samoa"),
	AZ("Azerbaijan"),
	BA("Bosnia and Herzegovina"),
	BE("Belgium"),
	BG("Bulgaria"),
	BH("Bahrain"),
	BI("Burundi"),
	BM("Bermuda"),
	BN("Brunei"),
	BO("Bolivia"),
	BR("Brazil"),
	BS("Bahamas"),
	CA("Canada"),
	CH("Switzerland"),
	CO("Colombia"),
	CR("Costa Rica"),
	CS("Serbia and Montenegro"),
	CU("Cuba"),
	CV("Cape Verde"),
	CY("Cyprus"),
	DE("Germany"),
	DZ("Algeria"),
	EE("Estonia"),
	ES("Spain"),
	ET("Ethiopia"),
	FI("Finland"),
	FJ("Fiji"),
	FO("Faroe Islands"),
	FR("France"),
	GA("Gabon"),
	GD("Grenada"),
	GL("Greenland"),
	GN("Guinea"),
	GU("Guam"),
	HR("Croatia"),
	HT("Haiti"),
	HU("Hungary"),
	ID("Indonesia"),
	IE("Ireland"),
	IN("India"),
	IO("British Indian Ocean Territory"),
	IS("Iceland"),
	IT("Italy"),
	KG("Kyrgyzstan"),
	KI("Kiribati"),
	KM("Comoros"),
	KN("Saint Kitts And Nevis"),
	KR("South Korea"),
	KW("Kuwait"),
	KY("Cayman Islands"),
	LB("Lebanon"),
	LI("Liechtenstein"),
	LT("Lithuania"),
	LU("Luxembourg"),
	LV("Latvia"),
	MG("Madagascar"),
	MH("Marshall Islands"),
	MK("Macedonia"),
	ML("Mali"),
	MN("Mongolia"),
	MO("Macao"),
	MR("Mauritania"),
	MS("Montserrat"),
	MT("Malta"),
	MY("Malaysia"),
	NA("Namibia"),
	NE("Niger"),
	NG("Nigeria"),
	NL("Netherlands"),
	NO("Norway"),
	NR("Nauru"),
	OM("Oman"),
	PA("Panama"),
	PL("Poland"),
	PS("Palestine"),
	PT("Portugal"),
	RO("Romania"),
	RU("Russia"),
	RW("Rwanda"),
	SA("Saudi Arabia"),
	SC("Seychelles"),
	SD("Sudan"),
	SE("Sweden"),
	SG("Singapore"),
	SI("Slovenia"),
	SK("Slovakia"),
	SL("Sierra Leone"),
	SM("San Marino"),
	SN("Senegal"),
	SO("Somalia"),
	SR("Suriname"),
	SS("South Sudan"),
	ST("Sao Tome And Principe"),
	SV("El Salvador"),
	TG("Togo"),
	TH("Thailand"),
	TK("Tokelau"),
	TL("Timor-Leste"),
	TN("Tunisia"),
	TO("Tonga"),
	TR("Turkey"),
	TT("Trinidad and Tobago"),
	TW("Taiwan"),
	UG("Uganda"),
	UZ("Uzbekistan"),
	VE("Venezuela"),
	VI("U.S. Virgin Islands"),
	ZA("South Africa");

	/**
	 * Create a description to get the enum's description
	 */
	private String description;
	
	Countries (String description){
		this.description = description;
	}

	public String getDescription() {
		return description;
	}
}
